"""Create 600 dpi TIFF delivery assets from native 600 dpi chart renders.

The source PNGs are generated by the project plotting scripts from released aggregate
outputs or authorized private data. TIFF conversion does not alter numeric geometry.
"""
from pathlib import Path
from PIL import Image
import json
ROOT=Path(__file__).resolve().parents[1]
files=[
 ROOT/'results/reviewer_r1/figures/distribution_diagnostics_annotated.png',
 ROOT/'results/reviewer_r3/figures/r3_estimator_specific_coefficient_panels.png',
 ROOT/'results/reviewer_r1/figures/ols_count_residual_diagnostic.png',
 ROOT/'results/reviewer_r1/figures/selection_love_plot.png',
 ROOT/'results/reviewer_r2/figures/r2_estimator_sample_retention.png',
 ROOT/'results/reviewer_r3/figures/r3_ppml_diagnostics.png',
 ROOT/'results/reviewer_r2/figures/r2_timing_year_support.png',
]
manifest=[]
for png in files:
 im=Image.open(png)
 if not im.info.get('dpi') or im.info['dpi'][0]<599:
  raise RuntimeError(f'{png} is not a native 600 dpi render: {im.info.get("dpi")}')
 tif=png.with_suffix('.tiff')
 im.save(tif,compression='tiff_lzw',dpi=(600,600))
 manifest.append({'source_png':str(png.relative_to(ROOT)),'delivery_tiff':str(tif.relative_to(ROOT)),'width_px':im.width,'height_px':im.height,'dpi':600,'format':'TIFF (LZW)','status':'native 600 dpi source render converted without resizing'})
out=ROOT/'results/figures/publication_figure_asset_manifest.json'
out.parent.mkdir(parents=True,exist_ok=True)
out.write_text(json.dumps(manifest,indent=2),encoding='utf-8')
print(json.dumps(manifest,indent=2))
